openapi: 3.0.3
info:
  description: |
    ___
    This is the REST API for controlling the BrowserUp MitmProxy.
    The BrowserUp MitmProxy is a swiss army knife for automated testing that
    captures HTTP traffic in HAR files. It is also useful for Selenium/Cypress tests.
    ___
  title: BrowserUp MitmProxy
  version: 1.0.0
  x-logo:
    url: logo.png
servers:
- description: The development API server
  url: "http://localhost:{port}/"
  variables:
    port:
      default: "48088"
      enum:
      - "48088"
tags:
- description: BrowserUp MitmProxy REST API
  name: The BrowserUp MitmProxy API
paths:
  /har:
    get:
      description: Get the current HAR.
      operationId: getHarLog
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Har'
          description: The current Har file.
      tags:
      - BrowserUpProxy
    put:
      description: Starts a fresh HAR capture session.
      operationId: resetHarLog
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Har'
          description: The current Har file.
      tags:
      - BrowserUpProxy
  /har/page:
    post:
      description: Starts a fresh HAR Page (Step) in the current active HAR to group
        requests.
      operationId: newPage
      parameters:
      - description: The unique title for this har page/step.
        explode: false
        in: path
        name: title
        required: true
        schema:
          pattern: "/[a-zA-Z-_]{4,25}/"
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Har'
          description: The current Har file.
      tags:
      - BrowserUpProxy
  /verify/present/{name}:
    post:
      description: Verify at least one matching item is present in the captured traffic
      operationId: verifyPresent
      parameters:
      - description: The unique name for this verification operation
        explode: false
        in: path
        name: name
        required: true
        schema:
          pattern: "/[a-zA-Z-_]{4,25}/"
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatchCriteria'
        description: Match criteria to select requests - response pairs for size tests
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyResult'
          description: The traffic conformed to the time criteria.
        "422":
          description: The MatchCriteria are invalid.
      tags:
      - BrowserUpProxy
  /verify/not_present/{name}:
    post:
      description: Verify no matching items are present in the captured traffic
      operationId: verifyNotPresent
      parameters:
      - description: The unique name for this verification operation
        explode: false
        in: path
        name: name
        required: true
        schema:
          pattern: "/[a-zA-Z-_]{4,25}/"
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatchCriteria'
        description: Match criteria to select requests - response pairs for size tests
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyResult'
          description: The traffic had no matching items
        "422":
          description: The MatchCriteria are invalid.
      tags:
      - BrowserUpProxy
  /verify/size/{size}/{name}:
    post:
      description: Verify matching items in the captured traffic meet the size criteria
      operationId: verifySize
      parameters:
      - description: "The size used for comparison, in kilobytes"
        explode: false
        in: path
        name: size
        required: true
        schema:
          minimum: 0
          type: integer
        style: simple
      - description: The unique name for this verification operation
        explode: false
        in: path
        name: name
        required: true
        schema:
          pattern: "/[a-zA-Z-_]{4,25}/"
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatchCriteria'
        description: Match criteria to select requests - response pairs for size tests
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyResult'
          description: The traffic conformed to the size criteria.
        "422":
          description: The MatchCriteria are invalid.
      tags:
      - BrowserUpProxy
  /verify/sla/{time}/{name}:
    post:
      description: Verify each traffic item matching the criteria meets is below SLA
        time
      operationId: verifySLA
      parameters:
      - description: The time used for comparison
        explode: false
        in: path
        name: time
        required: true
        schema:
          minimum: 0
          type: integer
        style: simple
      - description: The unique name for this verification operation
        explode: false
        in: path
        name: name
        required: true
        schema:
          pattern: "/[a-zA-Z-_]{4,25}/"
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MatchCriteria'
        description: Match criteria to select requests - response pairs for size tests
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VerifyResult'
          description: The traffic conformed to the time criteria.
        "422":
          description: The MatchCriteria are invalid.
      tags:
      - BrowserUpProxy
  /har/errors:
    post:
      description: Add Custom Error to the captured traffic har
      operationId: addError
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Error'
        description: "Receives an error to track. Internally, the error is stored\
          \ in an array in the har under the _errors key"
        required: true
      responses:
        "204":
          description: The Error was added.
        "422":
          description: The Error was invalid.
      tags:
      - BrowserUpProxy
  /har/counters:
    post:
      description: Add Custom Counter to the captured traffic har
      operationId: addCounter
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Counter'
        description: "Receives a new counter to add. The counter is stored, under\
          \ the hood, in an array in the har under the _counters key"
        required: true
      responses:
        "204":
          description: The counter was added.
        "422":
          description: The counter was invalid.
      tags:
      - BrowserUpProxy
  /healthcheck:
    get:
      description: Get the healthcheck
      operationId: healthcheck
      responses:
        "200":
          description: OK means all is well.
      tags:
      - BrowserUpProxy
components:
  schemas:
    PageTiming:
      properties:
        onContentLoad:
          description: onContentLoad per the browser
          type: number
        onLoad:
          description: onLoad per the browser
          type: number
        _firstInputDelay:
          description: firstInputDelay from the browser
          type: number
        _firstPaint:
          description: firstPaint from the browser
          type: number
        _cumulativeLayoutShift:
          description: cumulativeLayoutShift metric from the browser
          type: number
        _largestContentfulPaint:
          description: largestContentfulPaint from the browser
          type: number
        _domInteractive:
          description: domInteractive from the browser
          type: number
        _firstContentfulPaint:
          description: firstContentfulPaint from the browser
          type: number
        _dns:
          description: dns lookup time from the browser
          type: number
        _ssl:
          description: Ssl connect time from the browser
          type: number
        _timeToFirstByte:
          description: Time to first byte of the page's first request per the browser
          type: number
        _href:
          description: "Top level href, including hashtag, etc per the browser"
          type: string
      type: object
    NameValuePair:
      properties:
        name:
          description: Name to match
          type: string
        value:
          description: Value to match
          type: string
      type: object
    MatchCriteria:
      description: |-
        A set of criteria for filtering HTTP Requests and Responses.
                                 Criteria are AND based, and use python regular expressions for string comparison
      example:
        request_cookie: ""
        response_cookie: ""
        json_path: json_path
        error_if_no_traffic: true
        url: url
        content: content
        response_header: ""
        content_type: content_type
        request_header: ""
        json_schema: json_schema
        json_valid: true
        page: page
        websocket_message: websocket_message
        status: status
      properties:
        url:
          description: Request URL regexp to match
          externalDocs:
            description: Python Regex
            url: https://docs.python.org/3/howto/regex.html
          type: string
        page:
          description: current|all
          externalDocs:
            description: Python Regex
            url: https://docs.python.org/3/howto/regex.html
          type: string
        status:
          description: HTTP Status code to match.
          externalDocs:
            description: Python Regex
            url: https://docs.python.org/3/howto/regex.html
          type: string
        content:
          description: Body content regexp content to match
          externalDocs:
            description: Python Regex
            url: https://docs.python.org/3/howto/regex.html
          type: string
        content_type:
          description: Content type
          externalDocs:
            description: Python Regex
            url: https://docs.python.org/3/howto/regex.html
          type: string
        websocket_message:
          description: Websocket message text to match
          externalDocs:
            description: Python Regex
            url: https://docs.python.org/3/howto/regex.html
          type: string
        request_header:
          allOf:
          - $ref: '#/components/schemas/NameValuePair'
          externalDocs:
            description: Python Regex
            url: https://docs.python.org/3/howto/regex.html
        request_cookie:
          allOf:
          - $ref: '#/components/schemas/NameValuePair'
          externalDocs:
            description: Python Regex
            url: https://docs.python.org/3/howto/regex.html
        response_header:
          allOf:
          - $ref: '#/components/schemas/NameValuePair'
          externalDocs:
            description: Python Regex
            url: https://docs.python.org/3/howto/regex.html
        response_cookie:
          allOf:
          - $ref: '#/components/schemas/NameValuePair'
          externalDocs:
            description: Python Regex
            url: https://docs.python.org/3/howto/regex.html
        json_valid:
          description: Is valid JSON
          type: boolean
        json_path:
          description: Has JSON path
          type: string
        json_schema:
          description: Validates against passed JSON schema
          type: string
        error_if_no_traffic:
          default: true
          description: "If the proxy has NO traffic at all, return error"
          type: boolean
      type: object
    VerifyResult:
      example:
        result: true
        name: name
        type: type
      properties:
        result:
          description: Result True / False
          type: boolean
        name:
          description: Name
          type: string
        type:
          description: Type
          type: string
      type: object
    Error:
      example:
        name: name
        details: details
      properties:
        name:
          description: Name of the Error to add. Stored in har under _errors
          type: string
        details:
          description: Short details of the error
          type: string
      type: object
    Counter:
      example:
        name: name
        value: 0.8008281904610115
      properties:
        name:
          description: Name of Custom Counter to add to the page under _counters
          type: string
        value:
          description: Value for the counter
          format: double
          type: number
      type: object
    LargestContentfulPaint:
      additionalProperties: true
      example:
        size: 0
        domPath: domPath
        startTime: 0
        tag: tag
      properties:
        startTime:
          default: -1
          format: int64
          minimum: -1
          type: integer
        size:
          default: -1
          format: int64
          minimum: -1
          type: integer
        domPath:
          default: ""
          type: string
        tag:
          default: ""
          type: string
      type: object
    WebSocketMessage:
      example:
        data: data
        time: 7.058770351582356
        type: type
        opcode: 0.8851374739011653
      properties:
        type:
          type: string
        opcode:
          type: number
        data:
          type: string
        time:
          type: number
      required:
      - data
      - opcode
      - time
      - type
      type: object
    Header:
      example:
        name: name
        comment: comment
        value: value
      properties:
        name:
          type: string
        value:
          type: string
        comment:
          type: string
      required:
      - name
      - value
      type: object
    Action:
      additionalProperties: false
      properties:
        name:
          type: string
        id:
          type: string
        className:
          type: string
        tagName:
          type: string
        xpath:
          type: string
        dataAttributes:
          type: string
        formName:
          type: string
        content:
          type: string
      type: object
    PageTimings:
      additionalProperties: true
      example:
        _href: _href
        _ssl: 0
        _firstPaint: 0
        _cumulativeLayoutShift: -0.29385987
        _dns: 0
        _largestContentfulPaint:
          size: 0
          domPath: domPath
          startTime: 0
          tag: tag
        _firstInputDelay: -0.5854392
        _domInteractive: 0
        _timeToFirstByte: 0
        _firstContentfulPaint: 0
        onContentLoad: 0
        onLoad: 0
        comment: comment
      properties:
        onContentLoad:
          default: -1
          format: int64
          minimum: -1
          type: integer
        onLoad:
          default: -1
          format: int64
          minimum: -1
          type: integer
        _href:
          default: ""
          type: string
        _dns:
          default: -1
          format: int64
          minimum: -1
          type: integer
        _ssl:
          default: -1
          format: int64
          minimum: -1
          type: integer
        _timeToFirstByte:
          default: -1
          format: int64
          minimum: -1
          type: integer
        _cumulativeLayoutShift:
          default: -1
          format: float
          minimum: -1
          type: number
        _largestContentfulPaint:
          $ref: '#/components/schemas/LargestContentfulPaint'
        _firstPaint:
          default: -1
          format: int64
          minimum: -1
          type: integer
        _firstInputDelay:
          default: -1
          format: float
          minimum: -1
          type: number
        _domInteractive:
          default: -1
          format: int64
          minimum: -1
          type: integer
        _firstContentfulPaint:
          default: -1
          format: int64
          minimum: -1
          type: integer
        comment:
          type: string
      required:
      - onContentLoad
      - onLoad
      type: object
    Har:
      additionalProperties: true
      example:
        log:
          creator:
            name: name
            comment: comment
            version: version
          entries:
          - startedDateTime: 2000-01-23T04:56:07.000+00:00
            request:
              headers:
              - name: name
                comment: comment
                value: value
              - name: name
                comment: comment
                value: value
              httpVersion: httpVersion
              method: method
              headersSize: 1
              bodySize: 6
              comment: comment
              queryString:
              - name: name
                comment: comment
                value: value
              - name: name
                comment: comment
                value: value
              postData:
                mimeType: mimeType
                text: text
                params:
                - fileName: fileName
                  name: name
                  comment: comment
                  value: value
                  contentType: contentType
                - fileName: fileName
                  name: name
                  comment: comment
                  value: value
                  contentType: contentType
              url: https://openapi-generator.tech
              cookies:
              - path: path
                expires: expires
                domain: domain
                name: name
                comment: comment
                httpOnly: true
                secure: true
                value: value
              - path: path
                expires: expires
                domain: domain
                name: name
                comment: comment
                httpOnly: true
                secure: true
                value: value
            cache:
              afterRequest:
                expires: expires
                hitCount: 2
                lastAccess: lastAccess
                eTag: eTag
                comment: comment
              comment: comment
              beforeRequest:
                expires: expires
                hitCount: 2
                lastAccess: lastAccess
                eTag: eTag
                comment: comment
            _webSocketMessages:
            - data: data
              time: 7.058770351582356
              type: type
              opcode: 0.8851374739011653
            - data: data
              time: 7.058770351582356
              type: type
              opcode: 0.8851374739011653
            response:
              headers:
              - name: name
                comment: comment
                value: value
              - name: name
                comment: comment
                value: value
              httpVersion: httpVersion
              redirectURL: redirectURL
              statusText: statusText
              headersSize: 6
              bodySize: 1
              comment: comment
              cookies:
              - path: path
                expires: expires
                domain: domain
                name: name
                comment: comment
                httpOnly: true
                secure: true
                value: value
              - path: path
                expires: expires
                domain: domain
                name: name
                comment: comment
                httpOnly: true
                secure: true
                value: value
              content:
                _videoBufferedPercent: 0
                _videoDroppedFrames: 0
                mimeType: mimeType
                encoding: encoding
                _videoDecodedByteCount: 0
                _videoTotalFrames: 0
                size: 1
                _videoStallCount: 0
                _videoErrorCount: 0
                comment: comment
                text: text
                _videoAudioBytesDecoded: 0
                compression: 4
                _videoWaitingCount: 0
              status: 7
            serverIPAddress: serverIPAddress
            timings:
              receive: 0
              wait: 0
              blocked: 0
              dns: 0
              comment: comment
              send: 0
              ssl: 0
              connect: 0
            connection: connection
            comment: comment
            time: 0
            pageref: pageref
          - startedDateTime: 2000-01-23T04:56:07.000+00:00
            request:
              headers:
              - name: name
                comment: comment
                value: value
              - name: name
                comment: comment
                value: value
              httpVersion: httpVersion
              method: method
              headersSize: 1
              bodySize: 6
              comment: comment
              queryString:
              - name: name
                comment: comment
                value: value
              - name: name
                comment: comment
                value: value
              postData:
                mimeType: mimeType
                text: text
                params:
                - fileName: fileName
                  name: name
                  comment: comment
                  value: value
                  contentType: contentType
                - fileName: fileName
                  name: name
                  comment: comment
                  value: value
                  contentType: contentType
              url: https://openapi-generator.tech
              cookies:
              - path: path
                expires: expires
                domain: domain
                name: name
                comment: comment
                httpOnly: true
                secure: true
                value: value
              - path: path
                expires: expires
                domain: domain
                name: name
                comment: comment
                httpOnly: true
                secure: true
                value: value
            cache:
              afterRequest:
                expires: expires
                hitCount: 2
                lastAccess: lastAccess
                eTag: eTag
                comment: comment
              comment: comment
              beforeRequest:
                expires: expires
                hitCount: 2
                lastAccess: lastAccess
                eTag: eTag
                comment: comment
            _webSocketMessages:
            - data: data
              time: 7.058770351582356
              type: type
              opcode: 0.8851374739011653
            - data: data
              time: 7.058770351582356
              type: type
              opcode: 0.8851374739011653
            response:
              headers:
              - name: name
                comment: comment
                value: value
              - name: name
                comment: comment
                value: value
              httpVersion: httpVersion
              redirectURL: redirectURL
              statusText: statusText
              headersSize: 6
              bodySize: 1
              comment: comment
              cookies:
              - path: path
                expires: expires
                domain: domain
                name: name
                comment: comment
                httpOnly: true
                secure: true
                value: value
              - path: path
                expires: expires
                domain: domain
                name: name
                comment: comment
                httpOnly: true
                secure: true
                value: value
              content:
                _videoBufferedPercent: 0
                _videoDroppedFrames: 0
                mimeType: mimeType
                encoding: encoding
                _videoDecodedByteCount: 0
                _videoTotalFrames: 0
                size: 1
                _videoStallCount: 0
                _videoErrorCount: 0
                comment: comment
                text: text
                _videoAudioBytesDecoded: 0
                compression: 4
                _videoWaitingCount: 0
              status: 7
            serverIPAddress: serverIPAddress
            timings:
              receive: 0
              wait: 0
              blocked: 0
              dns: 0
              comment: comment
              send: 0
              ssl: 0
              connect: 0
            connection: connection
            comment: comment
            time: 0
            pageref: pageref
          pages:
          - startedDateTime: 2000-01-23T04:56:07.000+00:00
            pageTimings:
              _href: _href
              _ssl: 0
              _firstPaint: 0
              _cumulativeLayoutShift: -0.29385987
              _dns: 0
              _largestContentfulPaint:
                size: 0
                domPath: domPath
                startTime: 0
                tag: tag
              _firstInputDelay: -0.5854392
              _domInteractive: 0
              _timeToFirstByte: 0
              _firstContentfulPaint: 0
              onContentLoad: 0
              onLoad: 0
              comment: comment
            comment: comment
            id: id
            _verifications:
            - result: true
              name: name
              type: type
            - result: true
              name: name
              type: type
            title: title
            _counters:
            - name: name
              value: 0.8008281904610115
            - name: name
              value: 0.8008281904610115
            _errors:
            - name: name
              details: details
            - name: name
              details: details
          - startedDateTime: 2000-01-23T04:56:07.000+00:00
            pageTimings:
              _href: _href
              _ssl: 0
              _firstPaint: 0
              _cumulativeLayoutShift: -0.29385987
              _dns: 0
              _largestContentfulPaint:
                size: 0
                domPath: domPath
                startTime: 0
                tag: tag
              _firstInputDelay: -0.5854392
              _domInteractive: 0
              _timeToFirstByte: 0
              _firstContentfulPaint: 0
              onContentLoad: 0
              onLoad: 0
              comment: comment
            comment: comment
            id: id
            _verifications:
            - result: true
              name: name
              type: type
            - result: true
              name: name
              type: type
            title: title
            _counters:
            - name: name
              value: 0.8008281904610115
            - name: name
              value: 0.8008281904610115
            _errors:
            - name: name
              details: details
            - name: name
              details: details
          browser:
            name: name
            comment: comment
            version: version
          comment: comment
          version: version
      properties:
        log:
          $ref: '#/components/schemas/Har_log'
      required:
      - log
      type: object
    HarEntry:
      example:
        startedDateTime: 2000-01-23T04:56:07.000+00:00
        request:
          headers:
          - name: name
            comment: comment
            value: value
          - name: name
            comment: comment
            value: value
          httpVersion: httpVersion
          method: method
          headersSize: 1
          bodySize: 6
          comment: comment
          queryString:
          - name: name
            comment: comment
            value: value
          - name: name
            comment: comment
            value: value
          postData:
            mimeType: mimeType
            text: text
            params:
            - fileName: fileName
              name: name
              comment: comment
              value: value
              contentType: contentType
            - fileName: fileName
              name: name
              comment: comment
              value: value
              contentType: contentType
          url: https://openapi-generator.tech
          cookies:
          - path: path
            expires: expires
            domain: domain
            name: name
            comment: comment
            httpOnly: true
            secure: true
            value: value
          - path: path
            expires: expires
            domain: domain
            name: name
            comment: comment
            httpOnly: true
            secure: true
            value: value
        cache:
          afterRequest:
            expires: expires
            hitCount: 2
            lastAccess: lastAccess
            eTag: eTag
            comment: comment
          comment: comment
          beforeRequest:
            expires: expires
            hitCount: 2
            lastAccess: lastAccess
            eTag: eTag
            comment: comment
        _webSocketMessages:
        - data: data
          time: 7.058770351582356
          type: type
          opcode: 0.8851374739011653
        - data: data
          time: 7.058770351582356
          type: type
          opcode: 0.8851374739011653
        response:
          headers:
          - name: name
            comment: comment
            value: value
          - name: name
            comment: comment
            value: value
          httpVersion: httpVersion
          redirectURL: redirectURL
          statusText: statusText
          headersSize: 6
          bodySize: 1
          comment: comment
          cookies:
          - path: path
            expires: expires
            domain: domain
            name: name
            comment: comment
            httpOnly: true
            secure: true
            value: value
          - path: path
            expires: expires
            domain: domain
            name: name
            comment: comment
            httpOnly: true
            secure: true
            value: value
          content:
            _videoBufferedPercent: 0
            _videoDroppedFrames: 0
            mimeType: mimeType
            encoding: encoding
            _videoDecodedByteCount: 0
            _videoTotalFrames: 0
            size: 1
            _videoStallCount: 0
            _videoErrorCount: 0
            comment: comment
            text: text
            _videoAudioBytesDecoded: 0
            compression: 4
            _videoWaitingCount: 0
          status: 7
        serverIPAddress: serverIPAddress
        timings:
          receive: 0
          wait: 0
          blocked: 0
          dns: 0
          comment: comment
          send: 0
          ssl: 0
          connect: 0
        connection: connection
        comment: comment
        time: 0
        pageref: pageref
      properties:
        pageref:
          type: string
        startedDateTime:
          format: date-time
          type: string
        time:
          format: int64
          minimum: 0
          type: integer
        request:
          $ref: '#/components/schemas/HarEntry_request'
        response:
          $ref: '#/components/schemas/HarEntry_response'
        cache:
          $ref: '#/components/schemas/HarEntry_cache'
        timings:
          $ref: '#/components/schemas/HarEntry_timings'
        serverIPAddress:
          type: string
        _webSocketMessages:
          items:
            $ref: '#/components/schemas/WebSocketMessage'
          type: array
        connection:
          type: string
        comment:
          type: string
      required:
      - cache
      - request
      - response
      - startedDateTime
      - time
      - timings
      type: object
    CustomHarData:
      minProperties: 1
      type: object
    Page:
      additionalProperties: true
      example:
        startedDateTime: 2000-01-23T04:56:07.000+00:00
        pageTimings:
          _href: _href
          _ssl: 0
          _firstPaint: 0
          _cumulativeLayoutShift: -0.29385987
          _dns: 0
          _largestContentfulPaint:
            size: 0
            domPath: domPath
            startTime: 0
            tag: tag
          _firstInputDelay: -0.5854392
          _domInteractive: 0
          _timeToFirstByte: 0
          _firstContentfulPaint: 0
          onContentLoad: 0
          onLoad: 0
          comment: comment
        comment: comment
        id: id
        _verifications:
        - result: true
          name: name
          type: type
        - result: true
          name: name
          type: type
        title: title
        _counters:
        - name: name
          value: 0.8008281904610115
        - name: name
          value: 0.8008281904610115
        _errors:
        - name: name
          details: details
        - name: name
          details: details
      properties:
        startedDateTime:
          format: date-time
          type: string
        id:
          type: string
        title:
          type: string
        _verifications:
          default: []
          items:
            $ref: '#/components/schemas/VerifyResult'
          type: array
        _counters:
          default: []
          items:
            $ref: '#/components/schemas/Counter'
          type: array
        _errors:
          default: []
          items:
            $ref: '#/components/schemas/Error'
          type: array
        pageTimings:
          $ref: '#/components/schemas/PageTimings'
        comment:
          type: string
      required:
      - id
      - pageTimings
      - startedDateTime
      - title
      type: object
    Har_log_creator:
      example:
        name: name
        comment: comment
        version: version
      properties:
        name:
          type: string
        version:
          type: string
        comment:
          type: string
      required:
      - name
      - version
      type: object
    Har_log:
      example:
        creator:
          name: name
          comment: comment
          version: version
        entries:
        - startedDateTime: 2000-01-23T04:56:07.000+00:00
          request:
            headers:
            - name: name
              comment: comment
              value: value
            - name: name
              comment: comment
              value: value
            httpVersion: httpVersion
            method: method
            headersSize: 1
            bodySize: 6
            comment: comment
            queryString:
            - name: name
              comment: comment
              value: value
            - name: name
              comment: comment
              value: value
            postData:
              mimeType: mimeType
              text: text
              params:
              - fileName: fileName
                name: name
                comment: comment
                value: value
                contentType: contentType
              - fileName: fileName
                name: name
                comment: comment
                value: value
                contentType: contentType
            url: https://openapi-generator.tech
            cookies:
            - path: path
              expires: expires
              domain: domain
              name: name
              comment: comment
              httpOnly: true
              secure: true
              value: value
            - path: path
              expires: expires
              domain: domain
              name: name
              comment: comment
              httpOnly: true
              secure: true
              value: value
          cache:
            afterRequest:
              expires: expires
              hitCount: 2
              lastAccess: lastAccess
              eTag: eTag
              comment: comment
            comment: comment
            beforeRequest:
              expires: expires
              hitCount: 2
              lastAccess: lastAccess
              eTag: eTag
              comment: comment
          _webSocketMessages:
          - data: data
            time: 7.058770351582356
            type: type
            opcode: 0.8851374739011653
          - data: data
            time: 7.058770351582356
            type: type
            opcode: 0.8851374739011653
          response:
            headers:
            - name: name
              comment: comment
              value: value
            - name: name
              comment: comment
              value: value
            httpVersion: httpVersion
            redirectURL: redirectURL
            statusText: statusText
            headersSize: 6
            bodySize: 1
            comment: comment
            cookies:
            - path: path
              expires: expires
              domain: domain
              name: name
              comment: comment
              httpOnly: true
              secure: true
              value: value
            - path: path
              expires: expires
              domain: domain
              name: name
              comment: comment
              httpOnly: true
              secure: true
              value: value
            content:
              _videoBufferedPercent: 0
              _videoDroppedFrames: 0
              mimeType: mimeType
              encoding: encoding
              _videoDecodedByteCount: 0
              _videoTotalFrames: 0
              size: 1
              _videoStallCount: 0
              _videoErrorCount: 0
              comment: comment
              text: text
              _videoAudioBytesDecoded: 0
              compression: 4
              _videoWaitingCount: 0
            status: 7
          serverIPAddress: serverIPAddress
          timings:
            receive: 0
            wait: 0
            blocked: 0
            dns: 0
            comment: comment
            send: 0
            ssl: 0
            connect: 0
          connection: connection
          comment: comment
          time: 0
          pageref: pageref
        - startedDateTime: 2000-01-23T04:56:07.000+00:00
          request:
            headers:
            - name: name
              comment: comment
              value: value
            - name: name
              comment: comment
              value: value
            httpVersion: httpVersion
            method: method
            headersSize: 1
            bodySize: 6
            comment: comment
            queryString:
            - name: name
              comment: comment
              value: value
            - name: name
              comment: comment
              value: value
            postData:
              mimeType: mimeType
              text: text
              params:
              - fileName: fileName
                name: name
                comment: comment
                value: value
                contentType: contentType
              - fileName: fileName
                name: name
                comment: comment
                value: value
                contentType: contentType
            url: https://openapi-generator.tech
            cookies:
            - path: path
              expires: expires
              domain: domain
              name: name
              comment: comment
              httpOnly: true
              secure: true
              value: value
            - path: path
              expires: expires
              domain: domain
              name: name
              comment: comment
              httpOnly: true
              secure: true
              value: value
          cache:
            afterRequest:
              expires: expires
              hitCount: 2
              lastAccess: lastAccess
              eTag: eTag
              comment: comment
            comment: comment
            beforeRequest:
              expires: expires
              hitCount: 2
              lastAccess: lastAccess
              eTag: eTag
              comment: comment
          _webSocketMessages:
          - data: data
            time: 7.058770351582356
            type: type
            opcode: 0.8851374739011653
          - data: data
            time: 7.058770351582356
            type: type
            opcode: 0.8851374739011653
          response:
            headers:
            - name: name
              comment: comment
              value: value
            - name: name
              comment: comment
              value: value
            httpVersion: httpVersion
            redirectURL: redirectURL
            statusText: statusText
            headersSize: 6
            bodySize: 1
            comment: comment
            cookies:
            - path: path
              expires: expires
              domain: domain
              name: name
              comment: comment
              httpOnly: true
              secure: true
              value: value
            - path: path
              expires: expires
              domain: domain
              name: name
              comment: comment
              httpOnly: true
              secure: true
              value: value
            content:
              _videoBufferedPercent: 0
              _videoDroppedFrames: 0
              mimeType: mimeType
              encoding: encoding
              _videoDecodedByteCount: 0
              _videoTotalFrames: 0
              size: 1
              _videoStallCount: 0
              _videoErrorCount: 0
              comment: comment
              text: text
              _videoAudioBytesDecoded: 0
              compression: 4
              _videoWaitingCount: 0
            status: 7
          serverIPAddress: serverIPAddress
          timings:
            receive: 0
            wait: 0
            blocked: 0
            dns: 0
            comment: comment
            send: 0
            ssl: 0
            connect: 0
          connection: connection
          comment: comment
          time: 0
          pageref: pageref
        pages:
        - startedDateTime: 2000-01-23T04:56:07.000+00:00
          pageTimings:
            _href: _href
            _ssl: 0
            _firstPaint: 0
            _cumulativeLayoutShift: -0.29385987
            _dns: 0
            _largestContentfulPaint:
              size: 0
              domPath: domPath
              startTime: 0
              tag: tag
            _firstInputDelay: -0.5854392
            _domInteractive: 0
            _timeToFirstByte: 0
            _firstContentfulPaint: 0
            onContentLoad: 0
            onLoad: 0
            comment: comment
          comment: comment
          id: id
          _verifications:
          - result: true
            name: name
            type: type
          - result: true
            name: name
            type: type
          title: title
          _counters:
          - name: name
            value: 0.8008281904610115
          - name: name
            value: 0.8008281904610115
          _errors:
          - name: name
            details: details
          - name: name
            details: details
        - startedDateTime: 2000-01-23T04:56:07.000+00:00
          pageTimings:
            _href: _href
            _ssl: 0
            _firstPaint: 0
            _cumulativeLayoutShift: -0.29385987
            _dns: 0
            _largestContentfulPaint:
              size: 0
              domPath: domPath
              startTime: 0
              tag: tag
            _firstInputDelay: -0.5854392
            _domInteractive: 0
            _timeToFirstByte: 0
            _firstContentfulPaint: 0
            onContentLoad: 0
            onLoad: 0
            comment: comment
          comment: comment
          id: id
          _verifications:
          - result: true
            name: name
            type: type
          - result: true
            name: name
            type: type
          title: title
          _counters:
          - name: name
            value: 0.8008281904610115
          - name: name
            value: 0.8008281904610115
          _errors:
          - name: name
            details: details
          - name: name
            details: details
        browser:
          name: name
          comment: comment
          version: version
        comment: comment
        version: version
      externalDocs:
        description: HAR (HTTP Archive) Log Format
        url: http://www.softwareishard.com/blog/har-12-spec/
      properties:
        version:
          type: string
        creator:
          $ref: '#/components/schemas/Har_log_creator'
        browser:
          $ref: '#/components/schemas/Har_log_creator'
        pages:
          items:
            $ref: '#/components/schemas/Page'
          type: array
        entries:
          items:
            $ref: '#/components/schemas/HarEntry'
          type: array
        comment:
          type: string
      required:
      - creator
      - entries
      - pages
      - version
      type: object
    HarEntry_request_cookies_inner:
      example:
        path: path
        expires: expires
        domain: domain
        name: name
        comment: comment
        httpOnly: true
        secure: true
        value: value
      properties:
        name:
          type: string
        value:
          type: string
        path:
          type: string
        domain:
          type: string
        expires:
          type: string
        httpOnly:
          type: boolean
        secure:
          type: boolean
        comment:
          type: string
      required:
      - name
      - value
      type: object
    HarEntry_request_queryString_inner:
      example:
        name: name
        comment: comment
        value: value
      properties:
        name:
          type: string
        value:
          type: string
        comment:
          type: string
      required:
      - name
      - value
      type: object
    HarEntry_request_postData_params_inner:
      example:
        fileName: fileName
        name: name
        comment: comment
        value: value
        contentType: contentType
      properties:
        name:
          type: string
        value:
          type: string
        fileName:
          type: string
        contentType:
          type: string
        comment:
          type: string
      type: object
    HarEntry_request_postData:
      description: Posted data info.
      example:
        mimeType: mimeType
        text: text
        params:
        - fileName: fileName
          name: name
          comment: comment
          value: value
          contentType: contentType
        - fileName: fileName
          name: name
          comment: comment
          value: value
          contentType: contentType
      properties:
        mimeType:
          type: string
        text:
          type: string
        params:
          items:
            $ref: '#/components/schemas/HarEntry_request_postData_params_inner'
          type: array
      required:
      - mimeType
    HarEntry_request:
      additionalProperties: true
      example:
        headers:
        - name: name
          comment: comment
          value: value
        - name: name
          comment: comment
          value: value
        httpVersion: httpVersion
        method: method
        headersSize: 1
        bodySize: 6
        comment: comment
        queryString:
        - name: name
          comment: comment
          value: value
        - name: name
          comment: comment
          value: value
        postData:
          mimeType: mimeType
          text: text
          params:
          - fileName: fileName
            name: name
            comment: comment
            value: value
            contentType: contentType
          - fileName: fileName
            name: name
            comment: comment
            value: value
            contentType: contentType
        url: https://openapi-generator.tech
        cookies:
        - path: path
          expires: expires
          domain: domain
          name: name
          comment: comment
          httpOnly: true
          secure: true
          value: value
        - path: path
          expires: expires
          domain: domain
          name: name
          comment: comment
          httpOnly: true
          secure: true
          value: value
      properties:
        method:
          type: string
        url:
          format: uri
          type: string
        httpVersion:
          type: string
        cookies:
          items:
            $ref: '#/components/schemas/HarEntry_request_cookies_inner'
          type: array
        headers:
          items:
            $ref: '#/components/schemas/Header'
          type: array
        queryString:
          items:
            $ref: '#/components/schemas/HarEntry_request_queryString_inner'
          type: array
        postData:
          $ref: '#/components/schemas/HarEntry_request_postData'
        headersSize:
          type: integer
        bodySize:
          type: integer
        comment:
          type: string
      required:
      - bodySize
      - cookies
      - headers
      - headersSize
      - httpVersion
      - method
      - queryString
      - url
      type: object
    HarEntry_response_content:
      example:
        _videoBufferedPercent: 0
        _videoDroppedFrames: 0
        mimeType: mimeType
        encoding: encoding
        _videoDecodedByteCount: 0
        _videoTotalFrames: 0
        size: 1
        _videoStallCount: 0
        _videoErrorCount: 0
        comment: comment
        text: text
        _videoAudioBytesDecoded: 0
        compression: 4
        _videoWaitingCount: 0
      properties:
        size:
          type: integer
        compression:
          type: integer
        mimeType:
          type: string
        text:
          type: string
        encoding:
          type: string
        _videoBufferedPercent:
          default: -1
          format: int64
          minimum: -1
          type: integer
        _videoStallCount:
          default: -1
          format: int64
          minimum: -1
          type: integer
        _videoDecodedByteCount:
          default: -1
          format: int64
          minimum: -1
          type: integer
        _videoWaitingCount:
          default: -1
          format: int64
          minimum: -1
          type: integer
        _videoErrorCount:
          default: -1
          format: int64
          minimum: -1
          type: integer
        _videoDroppedFrames:
          default: -1
          format: int64
          minimum: -1
          type: integer
        _videoTotalFrames:
          default: -1
          format: int64
          minimum: -1
          type: integer
        _videoAudioBytesDecoded:
          default: -1
          format: int64
          minimum: -1
          type: integer
        comment:
          type: string
      required:
      - mimeType
      - size
      type: object
    HarEntry_response:
      additionalProperties: true
      example:
        headers:
        - name: name
          comment: comment
          value: value
        - name: name
          comment: comment
          value: value
        httpVersion: httpVersion
        redirectURL: redirectURL
        statusText: statusText
        headersSize: 6
        bodySize: 1
        comment: comment
        cookies:
        - path: path
          expires: expires
          domain: domain
          name: name
          comment: comment
          httpOnly: true
          secure: true
          value: value
        - path: path
          expires: expires
          domain: domain
          name: name
          comment: comment
          httpOnly: true
          secure: true
          value: value
        content:
          _videoBufferedPercent: 0
          _videoDroppedFrames: 0
          mimeType: mimeType
          encoding: encoding
          _videoDecodedByteCount: 0
          _videoTotalFrames: 0
          size: 1
          _videoStallCount: 0
          _videoErrorCount: 0
          comment: comment
          text: text
          _videoAudioBytesDecoded: 0
          compression: 4
          _videoWaitingCount: 0
        status: 7
      properties:
        status:
          type: integer
        statusText:
          type: string
        httpVersion:
          type: string
        cookies:
          items:
            $ref: '#/components/schemas/HarEntry_request_cookies_inner'
          type: array
        headers:
          items:
            $ref: '#/components/schemas/Header'
          type: array
        content:
          $ref: '#/components/schemas/HarEntry_response_content'
        redirectURL:
          type: string
        headersSize:
          type: integer
        bodySize:
          type: integer
        comment:
          type: string
      required:
      - bodySize
      - content
      - cookies
      - headers
      - headersSize
      - httpVersion
      - redirectURL
      - status
      - statusText
      type: object
    HarEntry_cache_beforeRequest:
      example:
        expires: expires
        hitCount: 2
        lastAccess: lastAccess
        eTag: eTag
        comment: comment
      nullable: true
      properties:
        expires:
          type: string
        lastAccess:
          type: string
        eTag:
          type: string
        hitCount:
          type: integer
        comment:
          type: string
      required:
      - eTag
      - hitCount
      - lastAccess
      type: object
    HarEntry_cache:
      example:
        afterRequest:
          expires: expires
          hitCount: 2
          lastAccess: lastAccess
          eTag: eTag
          comment: comment
        comment: comment
        beforeRequest:
          expires: expires
          hitCount: 2
          lastAccess: lastAccess
          eTag: eTag
          comment: comment
      properties:
        beforeRequest:
          $ref: '#/components/schemas/HarEntry_cache_beforeRequest'
        afterRequest:
          $ref: '#/components/schemas/HarEntry_cache_beforeRequest'
        comment:
          type: string
    HarEntry_timings:
      example:
        receive: 0
        wait: 0
        blocked: 0
        dns: 0
        comment: comment
        send: 0
        ssl: 0
        connect: 0
      properties:
        dns:
          default: -1
          format: int64
          minimum: -1
          type: integer
        connect:
          default: -1
          format: int64
          minimum: -1
          type: integer
        blocked:
          default: -1
          format: int64
          minimum: -1
          type: integer
        send:
          default: -1
          format: int64
          minimum: -1
          type: integer
        wait:
          default: -1
          format: int64
          minimum: -1
          type: integer
        receive:
          default: -1
          format: int64
          minimum: -1
          type: integer
        ssl:
          default: -1
          format: int64
          minimum: -1
          type: integer
        comment:
          type: string
      required:
      - blocked
      - connect
      - dns
      - receive
      - send
      - ssl
      - wait
      type: object

